In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer 
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [3]:
df=pd.read_csv("C:\\Users\\adars\\Downloads\\mail_data.csv")
df.head(10)

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
5     spam  FreeMsg Hey there darling it's been 3 week's n...
6      ham  Even my brother is not like to speak with me. ...
7      ham  As per your request 'Melle Melle (Oru Minnamin...
8     spam  WINNER!! As a valued network customer you have...
9     spam  Had your mobile 11 months or more? U R entitle...

In [4]:
data=df.where(pd.notnull(df)," ")
data.head(10)

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
5     spam  FreeMsg Hey there darling it's been 3 week's n...
6      ham  Even my brother is not like to speak with me. ...
7      ham  As per your request 'Melle Melle (Oru Minnamin...
8     spam  WINNER!! As a valued network customer you have...
9     spam  Had your mobile 11 months or more? U R entitle...

In [17]:
data.info

<bound method DataFrame.info of      Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]>

In [5]:
df.shape

(5572, 2)

In [6]:
data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [7]:
data.loc[data["Category"]=="spam","Category"]=0
data.loc[data["Category"]=="ham","Category"]=1

In [8]:
X=data.Message
Y=data.Category

In [9]:
X

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: Message, Length: 5572, dtype: object

In [10]:
Y

0       1
1       1
2       0
3       1
4       1
       ..
5567    0
5568    1
5569    1
5570    1
5571    1
Name: Category, Length: 5572, dtype: object

In [12]:
X_train,X_test,y_train,y_test=train_test_split(X,Y,train_size=0.9)

In [ ]:
feature_extraction=TfidfVectorizer(min_df=1,stop_words="english",lowercase=True)

X_train_features=feature_extraction.fit_transform(X_train)
X_test_features=feature_extraction.fit_transform(X_test)
y_train=y_train.astype(int)
y_test=y_test.astype(int)

In [22]:

print(X_train_features)
print(X_test_features)
print(y_train)
print(y_test)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 38945 stored elements and shape (5014, 8005)>
  Coords	Values
  (0, 3542)	0.3274203909957469
  (0, 1818)	0.3918772672559594
  (0, 2227)	0.6272597423340508
  (0, 4307)	0.5880249234643152
  (1, 3077)	0.19196909504316845
  (1, 4897)	0.24874995901023875
  (1, 4276)	0.1169361849401195
  (1, 4914)	0.24874995901023875
  (1, 1914)	0.4584335258742785
  (1, 5027)	0.1838620861920659
  (1, 807)	0.17757380159319167
  (1, 4644)	0.1982573796420427
  (1, 2779)	0.2373237717882418
  (1, 4603)	0.14661441829809513
  (1, 3905)	0.2373237717882418
  (1, 543)	0.24874995901023875
  (1, 6209)	0.22921676293713925
  (1, 1598)	0.17151186716792516
  (1, 981)	0.24874995901023875
  (1, 6707)	0.18117620290191633
  (1, 2029)	0.24874995901023875
  (1, 3384)	0.15434817076383403
  (1, 787)	0.22921676293713925
  (2, 943)	0.2879941826566996
  (2, 1423)	0.2146044378192486
  :	:
  (5008, 3605)	0.4061862007684818
  (5009, 3522)	0.7796517827822246
  (5009, 6570)	0.6262133004053002
  (5010, 7458)	0.2740153299127946
  (5010, 7203)	0.3183926419066535
  (5010, 905)	0.4795370502161352
  (5010, 5259)	0.5154963620858152
  (5010, 4768)	0.5725813852185397
  (5011, 7677)	0.7464374489796254
  (5011, 3597)	0.6654555843636667
  (5012, 4234)	0.41056900627932946
  (5012, 3414)	0.38210540746564436
  (5012, 5096)	0.3261085040414366
  (5012, 1692)	0.48587423797483126
  (5012, 7928)	0.5856688630382798
  (5013, 3052)	0.2595902731016662
  (5013, 2269)	0.22531321082952507
  (5013, 7621)	0.43626993955493776
  (5013, 6618)	0.2740052910613525
  (5013, 7629)	0.2973242428805014
  (5013, 3300)	0.2776720163688498
  (5013, 3721)	0.3239906526385933
  (5013, 5298)	0.33958950237594165
  (5013, 1062)	0.33958950237594165
  (5013, 5300)	0.33958950237594165
<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4584 stored elements and shape (558, 2132)>
  Coords	Values
  (0, 799)	0.13190009208710834
  (0, 77)	0.1794437198344796
  (0, 2050)	0.2913524964493482
  (0, 1319)	0.20191790549616967
  (0, 1321)	0.34889126253522285
  (0, 1904)	0.3707104078132012
  (0, 1977)	0.24640412512596796
  (0, 1243)	0.20191790549616967
  (0, 1050)	0.12046042486913217
  (0, 1942)	0.14206993538966084
  (0, 154)	0.20191790549616967
  (0, 1946)	0.20191790549616967
  (0, 1839)	0.16288101824491047
  (0, 1190)	0.20191790549616967
  (0, 2109)	0.14382297832645566
  (0, 852)	0.20191790549616967
  (0, 1950)	0.15437427774879844
  (0, 1428)	0.20191790549616967
  (0, 111)	0.20191790549616967
  (0, 2018)	0.20191790549616967
  (0, 1324)	0.20191790549616967
  (0, 71)	0.1794437198344796
  (1, 1050)	0.20756008977306267
  (1, 1855)	0.2753284331245984
  (1, 1828)	0.3091916257021352
  :	:
  (553, 275)	0.3418942525388285
  (553, 29)	0.3418942525388285
  (554, 1345)	0.6038835187860913
  (554, 1739)	0.5417928088164833
  (554, 318)	0.5846240228157531
  (555, 799)	0.22290376022907582
  (555, 584)	0.2810328831606019
  (555, 943)	0.7958091352676383
  (555, 1211)	0.32546676771428457
  (555, 1534)	0.36344688139584835
  (556, 522)	0.2870429682194455
  (556, 579)	0.27625957601540363
  (556, 1656)	0.23395262740916226
  (556, 1077)	0.267448903053619
  (556, 66)	0.25999958520729516
  (556, 1399)	0.22650330956283848
  (556, 701)	0.2870429682194455
  (556, 304)	0.32053924386390226
  (556, 740)	0.32053924386390226
  (556, 41)	0.32053924386390226
  (556, 1429)	0.32053924386390226
  (556, 2017)	0.32053924386390226
  (557, 566)	0.5167625573058452
  (557, 2069)	0.675913207379218
  (557, 1866)	0.5254500884547088
3619    1
1086    1
1809    1
1049    1
3739    1
       ..
1883    1
3193    1
2332    1
4924    1
1382    1
Name: Category, Length: 5014, dtype: int64
3763    0
5039    1
3131    1
3929    1
4068    0
       ..
5377    0
3240    1
1784    1
2386    0
4560    1
Name: Category, Length: 558, dtype: int64

In [25]:
model=LogisticRegression()
model.fit(X_train_features,y_train)

LogisticRegression()

In [28]:
prediction_on_training_data=model.predict(X_train_features)
accuracy_0n_training_data=accuracy_score(y_train,prediction_on_training_data)
print("Accuracy on Training Data:",accuracy_0n_training_data)

Accuracy on Training Data: 0.9690865576386118

In [30]:
prediction_on_testing_data=model.predict(X_test_features)
accuracy_0n_testing_data=accuracy_score(y_test,prediction_on_testing_data)
print("Accuracy on Training Data:",accuracy_0n_testing_data)

ValueError: X has 2132 features, but LogisticRegression is expecting 8005 features as input.

In [31]:
input=[
    "Important mesage"
]
input_features=feature_extraction.fit_transform(input)
prediction=model.predict(input_features)
if(prediction[0]==1):
    print("Ham mail")
else:
    print("Spam mail")

ValueError: X has 2 features, but LogisticRegression is expecting 8005 features as input.